function config = getDefaultConfig()
%GETDEFAULTCONFIG Default application configuration for SI AI Workbench.

config = struct();
config.appVersion = "1.0.0";
config.appName = "Signal Integrity AI Workbench";

config.featureNames = { ...
    'tx_preemphasis_dB', ...
    'tx_jitter_ps', ...
    'trace_width_um', ...
    'trace_spacing_um', ...
    'substrate_thickness_mil', ...
    'er', ...
    'tan_delta', ...
    'rx_eq_dB', ...
    'rx_jitter_ps'};

config.featureDisplayNames = { ...
    'TX pre-emphasis', ...
    'TX jitter', ...
    'Trace width', ...
    'Trace spacing', ...
    'Substrate thickness', ...
    'Dielectric constant (Er)', ...
    'Loss tangent', ...
    'RX equalization', ...
    'RX jitter'};

config.featureUnits = { 'dB', 'ps', 'µm', 'µm', 'mil', '', '', 'dB', 'ps'};

config.featureDefaults = [ ...
    3.0; ...   % dB
    2.5; ...   % ps
    90; ...    % um
    100; ...   % um
    6.0; ...   % mil
    4.2; ...   % er
    0.018; ... % tan d
    4.0; ...   % rx eq dB
    2.0];       % rx jitter ps

config.featureLimits = [ ...
    0, 12; ...      % preemph
    0, 15; ...      % tx jitter
    40, 200; ...    % width
    50, 300; ...    % spacing
    2, 12; ...      % thickness mil
    3.0, 5.0; ...   % er
    0.005, 0.05; ...% tan d
    0, 15; ...      % rx eq
    0, 12];         % rx jitter

config.targetEyeHeight_mV = struct('label', "Eye height", 'unit', "mV", 'defaultSpec', 180);
config.targetEyeWidth_UI = struct('label', "Eye width", 'unit', "UI", 'defaultSpec', 0.28);

config.training = struct( ...
    'modelType', "deep", ...
    'maxEpochs', 120, ...
    'miniBatchSize', 32, ...
    'learningRate', 0.01, ...
    'hiddenLayerSizes', [64 32], ...
    'activation', "relu", ...
    'trainValSplit', 0.15, ...
    'randomSeed', 42);

config.paths = struct( ...
    'savedModels', "saved_models", ...
    'savedStudies', "saved_studies", ...
    'exports', "exports", ...
    'datasets', "datasets");

config.thresholds = struct( ...
    'eyeHeightPass_mV', 160, ...
    'eyeWidthPass_UI', 0.24);
end
