function toolboxStatusTable = buildToolboxStatusTable()
%BUILDTOOLBOXSTATUSTABLE Summarize required and optional MATLAB toolboxes.

toolboxNames = [ ...
    "MATLAB"; ...
    "Deep Learning Toolbox"; ...
    "Signal Integrity Toolbox"; ...
    "Statistics and Machine Learning Toolbox"; ...
    "Signal Processing Toolbox"; ...
    "Communications Toolbox"; ...
    "SerDes Toolbox"];

installedProductNames = {ver.Name};
toolboxIsInstalled = [ ...
    true; ...
    ~isempty(ver('nnet')); ...
    any(strcmp(installedProductNames, 'Signal Integrity Toolbox')); ...
    ~isempty(ver('stats')); ...
    ~isempty(ver('signal')); ...
    ~isempty(ver('comm')); ...
    ~isempty(ver('serdes'))];

toolboxRequirement = [ ...
    "Required"; ...
    "Required"; ...
    "Optional"; ...
    "Optional"; ...
    "Optional"; ...
    "Optional"; ...
    "Optional"];

toolboxPurpose = [ ...
    "Base language and numeric environment"; ...
    "Train the neural network regressors used in this repository"; ...
    "Generate serial-link simulations, kits, and exports for real training data"; ...
    "Compare with classical regression baselines if desired"; ...
    "Extend the project with waveform and frequency-domain analysis"; ...
    "Study communication signals and eye-diagram workflows"; ...
    "Connect the models to channel and equalization studies"];

toolboxStatus = repmat("Not installed", size(toolboxIsInstalled));
toolboxStatus(toolboxIsInstalled) = "Available";

toolboxStatusTable = table( ...
    toolboxNames, ...
    toolboxStatus, ...
    toolboxRequirement, ...
    toolboxPurpose, ...
    'VariableNames', {'Toolbox', 'Status', 'Requirement', 'Purpose'});
end
