function experimentCatalog = getExperimentCatalog()
%GETEXPERIMENTCATALOG Return the metadata for the published experiments.
%   EXPERIMENTCATALOG is a struct array describing the two regression tasks
%   reproduced in this repository: eye height and eye width.

experimentCatalog = [ ...
    createExperimentSpec( ...
        "eyeHeight", ...
        "Eye Height", ...
        "mV", ...
        [100 300 200], ...
        25, ...
        717, ...
        476, ...
        14, ...
        [148 253], ...
        [3.1 1.9 2.6], ...
        [3.4 2.7 3.1], ...
        [6.2 4.1 5.2], ...
        [5.9 6.1 6.3]), ...
    createExperimentSpec( ...
        "eyeWidth", ...
        "Eye Width", ...
        "UI", ...
        [10 20 20 30 20 20 10], ...
        15, ...
        509, ...
        203, ...
        12, ...
        [0.21 0.37], ...
        [0.006 0.006 0.008], ...
        [0.008 0.008 0.010], ...
        [7.9 8.1 8.7], ...
        [10.6 9.3 9.5])];
end

function experimentSpec = createExperimentSpec( ...
        key, ...
        displayName, ...
        units, ...
        hiddenLayerSizes, ...
        miniBatchSize, ...
        trainingSampleCount, ...
        validationSampleCount, ...
        featureCount, ...
        targetRange, ...
        referenceTrainingRmse, ...
        referenceValidationRmse, ...
        referenceTrainingMaxRelativeErrorPct, ...
        referenceValidationMaxRelativeErrorPct)

experimentSpec = struct( ...
    'key', key, ...
    'displayName', displayName, ...
    'units', units, ...
    'hiddenLayerSizes', hiddenLayerSizes, ...
    'miniBatchSize', miniBatchSize, ...
    'trainingSampleCount', trainingSampleCount, ...
    'validationSampleCount', validationSampleCount, ...
    'featureCount', featureCount, ...
    'targetRange', targetRange, ...
    'referenceTrainingRmse', referenceTrainingRmse, ...
    'referenceValidationRmse', referenceValidationRmse, ...
    'referenceTrainingMaxRelativeErrorPct', referenceTrainingMaxRelativeErrorPct, ...
    'referenceValidationMaxRelativeErrorPct', referenceValidationMaxRelativeErrorPct);
end
