function reference = paperFeatureReference()
%PAPERFEATUREREFERENCE Metadata for Lu et al. DNN channel models and column naming.
%
%   REFERENCE = signalIntegrity.paperFeatureReference() returns counts, sample
%   sizes, and canonical predictor column names for aligning Signal Integrity
%   Toolbox exports with this repository. The bundled conference PDF lists
%   individual parameter labels in Fig. 1(b) as a figure; use a full-text PDF
%   or your kit documentation to assign physical meaning to each column.

reference = struct();

reference.citation = "Lu, Tianjian, Ken Wu, Zhiping Yang, and Ju Sun, " + ...
    """High-Speed Channel Modeling with Deep Neural Network for Signal Integrity Analysis.""";

reference.figureNote = "Fig. 1(b) tabulates design parameters for the high-speed channel; " + ...
    "the short PDF in this repository renders those names inside the figure image.";

reference.eyeHeight = struct( ...
    'featureCount', 14, ...
    'trainingSampleCount', 717, ...
    'validationSampleCount', 476, ...
    'targetRange_mV', [148, 253], ...
    'predictorColumnNames', compose("height_p%02d", 1:14), ...
    'defaultTargetColumnName', "eyeHeight_mV");

reference.eyeWidth = struct( ...
    'featureCount', 12, ...
    'trainingSampleCount', 509, ...
    'validationSampleCount', 203, ...
    'targetRange_UI', [0.21, 0.37], ...
    'predictorColumnNames', compose("width_p%02d", 1:12), ...
    'defaultTargetColumnName', "eyeWidth_UI");

reference.suggestedSerialLinkMapping = ...
    "Map predictor columns to TX/RX equalization, package, and channel variables " + ...
    "exposed by Serial Link Designer or a Signal Integrity kit (PCIe, Ethernet, " + ...
    "CEI, USB, etc.). Parallel/DDR kits target different timing metrics unless you " + ...
    "change the experiment definition.";
end
