function printWorkflowWalkthroughIntro()
%PRINTWORKFLOWWALKTHROUGHINTRO Console narrative before running the example workflow.

fprintf('\n');
fprintf('================================================================================\n');
fprintf('  Signal Integrity context (MATLAB + this example)\n');
fprintf('================================================================================\n');

if signalIntegrity.isSignalIntegrityToolboxAvailable()
    fprintf(['  • Signal Integrity Toolbox is installed. Typical uses include link budget\n' ...
        '    and compliance workflows, channel/kit modeling, and integration with SerDes\n' ...
        '    and high-speed simulation stacks.\n']);
    fprintf('  • Tip: type doc signalintegrity for product examples and workflows.\n');
    fprintf(['  • This walkthrough will prefer native SI Toolbox eye plotting when it can\n' ...
        '    resolve a waveform source. Use workflow option siWaveformMatFile to point\n' ...
        '    at your own MAT/CSV export, or leave it empty to use the deterministic demo waveform.\n']);
    fprintf(['  • To browse available industry kits from MATLAB, run\n' ...
        '    scripts/openSignalIntegrityKitWorkflow from the repository.\n']);
else
    fprintf(['  • Signal Integrity Toolbox is not installed on this machine. You can still run\n' ...
        '    this repository: it trains surrogate models from tabular features and does not\n' ...
        '    require the toolbox. Install the toolbox when you want native SI workflows\n' ...
        '    for channel/kit generation and measurement-driven studies.\n']);
end

fprintf('\n');
fprintf('--------------------------------------------------------------------------------\n');
fprintf('  What this example is trying to do (plain language)\n');
fprintf('--------------------------------------------------------------------------------\n');
fprintf(['  • Goal: build fast regressors that estimate eye height (mV) and eye width (UI)\n' ...
    '    from a vector of channel / equalization / geometry descriptors (the inputs).\n']);
fprintf(['  • Why: full link simulation for every candidate design is expensive. A trained model\n' ...
    '    is a surrogate you can query quickly while exploring the design space.\n']);
fprintf(['  • Objective (training): minimize prediction error on held-out validation samples,\n' ...
    '    reported as RMSE and max relative error in the tables below.\n']);
fprintf(['  • Design variables (conceptual): the input features (length 14 for eye height,\n' ...
    '    12 for eye width in this project). In real studies these map to pre-layout\n' ...
    '    knobs, material choices, EQ settings, etc. The bundled synthetic data uses\n' ...
    '    abstract Gaussian features so the code runs everywhere.\n']);
fprintf(['  • Constraints: fixed network architecture per experiment, optimizer hyperparameters\n' ...
    '    from resolveWorkflowOptions, and the train/validation split implied by the dataset.\n']);

fprintf('\n');
fprintf('--------------------------------------------------------------------------------\n');
fprintf('  Figures you will see next\n');
fprintf('--------------------------------------------------------------------------------\n');
fprintf(['  • Training curves: RMSE vs iteration for each deep-learning optimizer (SGD, ...).\n' ...
    '  • Native Signal Integrity Toolbox eye diagrams when a waveform source is available.\n' ...
    '    Otherwise the walkthrough falls back to schematic eyes so the example still runs.\n']);
fprintf(['  • Prediction check: predicted vs actual on the validation set for the best run.\n' ...
    '  • Input sensitivity: magnitude of first-layer weights per feature (a rough view of\n' ...
    '    which inputs matter most, not a full sensitivity analysis).\n']);
fprintf('\n');
end
