function printWorkflowWalkthroughOutro(workflowResults)
%PRINTWORKFLOWWALKTHROUGHOUTRO Console narrative after training completes.

arguments
    workflowResults (1, 1) struct
end

fprintf('\n');
fprintf('================================================================================\n');
fprintf('  How to read the results (validation vs simulation)\n');
fprintf('================================================================================\n');

dataMode = string(workflowResults.options.dataMode);
if dataMode == "synthetic"
    fprintf(['  • Data mode is synthetic: targets were generated by a known random teacher\n' ...
        '    network. Validation compares the trained surrogate to that ground truth — it is\n' ...
        '    a numerical consistency check, not a SPICE/SerDes simulator match.\n']);
else
    fprintf(['  • Data mode is real: targets came from your MAT-file (measurements or exports).\n' ...
        '    Validation scores quantify how well the network interpolates the provided table.\n' ...
        '    Compare against a full simulator only when your MAT-file was built that way.\n']);
end

fprintf(['  • Using the trained model: call forward on the saved dlnetwork with a new feature\n' ...
    '    row (after applying the same normalization as training). The workflow stores the\n' ...
    '    best network per experiment inside workflowResults.experimentResults.<key>.\n']);
fprintf(['  • The Signal Integrity Toolbox eye figure is intentionally separate from the DNN:\n' ...
    '    it visualizes a waveform source (user export or demo waveform), while the neural\n' ...
    '    network predicts scalar eye metrics from tabular design parameters.\n']);
fprintf(['  • "Optimized design parameters" in the figures: the bar chart ranks input features\n' ...
    '    by first-layer weight magnitude for the best optimizer. That highlights influential\n' ...
    '    inputs for this dataset; it is not the same as a constrained optimizer over EQ taps.\n']);

fprintf('\n');
fprintf('--------------------------------------------------------------------------------\n');
fprintf('  Reference comparison\n');
fprintf('--------------------------------------------------------------------------------\n');
fprintf('  • The optimizer comparison tables include paper reference columns for RMSE metrics.\n');
fprintf('  • Your run can differ from the paper depending on data mode, seeds, and iterations.\n');
fprintf('\n');
end
